export interface CurrencyConfig {
  id: string;
  name: string;
  symbol: string;
  network: string;
  nowpaymentsTicker: string;
  plisioCurrency: string | null;
  minDepositMember: number;
  minDepositPastor: number;
  iconSlug: string;
  category: 'stablecoin' | 'major' | 'alt';
  sortOrder: number;
}

export const DEPOSIT_CURRENCIES: CurrencyConfig[] = [
  // === STABLECOINS ===
  {
    id: 'USDT_TRX',
    name: 'Tether',
    symbol: 'USDT',
    network: 'Tron TRC-20',
    nowpaymentsTicker: 'USDTTRC20',
    plisioCurrency: 'USDT_TRX',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'tether',
    category: 'stablecoin',
    sortOrder: 1,
  },
  {
    id: 'USDC_SOL',
    name: 'USD Coin',
    symbol: 'USDC',
    network: 'Solana',
    nowpaymentsTicker: 'USDCSOL',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'usd-coin',
    category: 'stablecoin',
    sortOrder: 2,
  },
  {
    id: 'USDT_BSC',
    name: 'Tether',
    symbol: 'USDT',
    network: 'BSC BEP-20',
    nowpaymentsTicker: 'USDTBSC',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'tether',
    category: 'stablecoin',
    sortOrder: 3,
  },
  {
    id: 'USDC_ERC20',
    name: 'USD Coin',
    symbol: 'USDC',
    network: 'Ethereum ERC-20',
    nowpaymentsTicker: 'USDC',
    plisioCurrency: 'USDC',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'usd-coin',
    category: 'stablecoin',
    sortOrder: 4,
  },
  {
    id: 'USDT_ERC20',
    name: 'Tether',
    symbol: 'USDT',
    network: 'Ethereum ERC-20',
    nowpaymentsTicker: 'USDTERC20',
    plisioCurrency: 'USDT',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'tether',
    category: 'stablecoin',
    sortOrder: 5,
  },

  // === MAJOR COINS ===
  {
    id: 'BTC',
    name: 'Bitcoin',
    symbol: 'BTC',
    network: 'Bitcoin',
    nowpaymentsTicker: 'BTC',
    plisioCurrency: 'BTC',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'bitcoin',
    category: 'major',
    sortOrder: 6,
  },
  {
    id: 'ETH',
    name: 'Ethereum',
    symbol: 'ETH',
    network: 'Ethereum',
    nowpaymentsTicker: 'ETH',
    plisioCurrency: 'ETH',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'ethereum',
    category: 'major',
    sortOrder: 7,
  },
  {
    id: 'SOL',
    name: 'Solana',
    symbol: 'SOL',
    network: 'Solana',
    nowpaymentsTicker: 'SOL',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'solana',
    category: 'major',
    sortOrder: 8,
  },
  {
    id: 'DOGE',
    name: 'Dogecoin',
    symbol: 'DOGE',
    network: 'Dogecoin',
    nowpaymentsTicker: 'DOGE',
    plisioCurrency: 'DOGE',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'dogecoin',
    category: 'major',
    sortOrder: 9,
  },
  {
    id: 'LTC',
    name: 'Litecoin',
    symbol: 'LTC',
    network: 'Litecoin',
    nowpaymentsTicker: 'LTC',
    plisioCurrency: 'LTC',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'litecoin',
    category: 'major',
    sortOrder: 10,
  },
  {
    id: 'XRP',
    name: 'XRP',
    symbol: 'XRP',
    network: 'XRP Ledger',
    nowpaymentsTicker: 'XRP',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'ripple',
    category: 'major',
    sortOrder: 11,
  },

  // === ALT COINS ===
  {
    id: 'ADA',
    name: 'Cardano',
    symbol: 'ADA',
    network: 'Cardano',
    nowpaymentsTicker: 'ADA',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'cardano',
    category: 'alt',
    sortOrder: 12,
  },
  {
    id: 'TRX',
    name: 'Tron',
    symbol: 'TRX',
    network: 'Tron',
    nowpaymentsTicker: 'TRX',
    plisioCurrency: 'TRX',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'tron',
    category: 'alt',
    sortOrder: 13,
  },
  {
    id: 'MATIC',
    name: 'Polygon',
    symbol: 'POL',
    network: 'Polygon',
    nowpaymentsTicker: 'MATIC',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'polygon-ecosystem-token',
    category: 'alt',
    sortOrder: 14,
  },
  {
    id: 'DOT',
    name: 'Polkadot',
    symbol: 'DOT',
    network: 'Polkadot',
    nowpaymentsTicker: 'DOT',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'polkadot',
    category: 'alt',
    sortOrder: 15,
  },
  {
    id: 'BCH',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    network: 'Bitcoin Cash',
    nowpaymentsTicker: 'BCH',
    plisioCurrency: 'BCH',
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'bitcoin-cash',
    category: 'alt',
    sortOrder: 16,
  },
  {
    id: 'SHIB',
    name: 'Shiba Inu',
    symbol: 'SHIB',
    network: 'Ethereum ERC-20',
    nowpaymentsTicker: 'SHIB',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'shiba-inu',
    category: 'alt',
    sortOrder: 17,
  },
  {
    id: 'AVAX',
    name: 'Avalanche',
    symbol: 'AVAX',
    network: 'Avalanche C-Chain',
    nowpaymentsTicker: 'AVAX',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'avalanche-2',
    category: 'alt',
    sortOrder: 18,
  },
  {
    id: 'LINK',
    name: 'Chainlink',
    symbol: 'LINK',
    network: 'Ethereum ERC-20',
    nowpaymentsTicker: 'LINK',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'chainlink',
    category: 'alt',
    sortOrder: 19,
  },
  {
    id: 'UNI',
    name: 'Uniswap',
    symbol: 'UNI',
    network: 'Ethereum ERC-20',
    nowpaymentsTicker: 'UNI',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'uniswap',
    category: 'alt',
    sortOrder: 20,
  },
  {
    id: 'KAS',
    name: 'Kaspa',
    symbol: 'KAS',
    network: 'Kaspa',
    nowpaymentsTicker: 'KAS',
    plisioCurrency: null,
    minDepositMember: 100,
    minDepositPastor: 200,
    iconSlug: 'kaspa',
    category: 'alt',
    sortOrder: 21,
  },
];

export function getCurrencyById(id: string): CurrencyConfig | undefined {
  return DEPOSIT_CURRENCIES.find(c => c.id === id);
}

export function getMinDeposit(currencyId: string, role: string): number {
  const currency = getCurrencyById(currencyId);
  if (!currency) return 200;
  return role === 'pastor' ? currency.minDepositPastor : currency.minDepositMember;
}
